theme: jekyll-theme-minimal
title: â˜•ğŸ©ğŸ‘‹
description: Prykhodchenko Mykyta CV
favicon: /assets/favicon.ico
email: nikitaprikhodchenko1@gmail.com
github_link: https://github.com/prykhodchenkomykyta
linkedin: https://www.linkedin.com/in/mykytaprykhodchenko/
